### Necessário para pegar o token
### Post
# @name loginAutenticado
POST http://localhost:40000/Login HTTP/1.1
content-type: application/json

{    
    "UserName": "admin",
    "Password": "admin"
}
### Seta o token
@accessToken = {{loginAutenticado.response.body.$.token}}
@username = {{loginAutenticado.response.body.$.username}}



### teste de inserção de recebimentos
POST http://localhost:40000/InsertRecebimentos HTTP/1.1
content-type: application/json
Authorization: Bearer {{accessToken}}

{    
    "ID": 0,
    "Descricao": "Recebimento Teste",
    "ID_ContaReceber": 1,
    "DataRecebimento": "2023-01-01",
    "ValorRecebido": 1000.00,
    "Removido": false
}

### teste de buscar todos os recebimentos
GET http://localhost:40000/getAllRecebimentos HTTP/1.1
content-type: application/json
Authorization: Bearer {{accessToken}}

{    
    
}

### teste de buscar recebimentos por ID
POST http://localhost:40000/getRecebimentosByID HTTP/1.1
content-type: application/json
Authorization: Bearer {{accessToken}}

{    
    "ID": 1
}



### teste de atualização de recebimentos
POST http://localhost:40000/updateRecebimentos HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InF3ZSIsImlhdCI6MTY5MTQzNTg3MSwiZXhwIjoxNjkxNDM2NDcxfQ.hAh0VyRfEXvYmhunlJALD-qda8pYr2zzAHobn1yua20

{    
    "ID": 0,
    "Descricao": "Recebimento Teste2",
    "ID_ContaReceber": 1,
    "DataRecebimento": "2023-01-01",
    "ValorRecebido": 1000.00,
    "Removido": false
}

### teste de atualização de recebimentos
POST http://localhost:40000/DeleteRecebimentos HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InF3ZSIsImlhdCI6MTY5MTQ5MDg3NCwiZXhwIjoxNjkxNDkxNDc0fQ.1ABhMgWYm8gGKy7q90GOPQpNoY5M1LLzpCltKxFjcEo

{    
    "alunoid": 55  
}